[package]
edition = "2021"
name = "create-uni_gui"
version = "0.0.0"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = [ "napi4" ] }
napi-derive = "2.12.2"
rfd = "0.15.1"
tao = "0.31.0"
webbrowser = "1.0.3"
wry = "0.47.2"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
