name: create-uni/info release CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'packages/info/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.com/

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: PNPM build
        working-directory: packages/info
        run: pnpm run build

      - name: Publish to NPM
        working-directory: packages/info
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
