name: update

on:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: update script
        run: pnpm run up

      - name: Commit and push if changes are made
        run: |
          git config --global user.email "734243792@qq.com"
          git config --global user.name "FliPPeDround"
          git add -A
          git commit -m "chore: update deps" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: 'chore: update deps'
          title: 'chore: update deps'
          body: Update dependencies
          branch: chore/update-deps
          delete-branch: true
          base: main
